# -*- coding: utf-8 -*-
"""
Build Portuguese article pages from the English page plus a gated translation.

    python tools/i18n/pt-2026/build_pt.py <site-root> <content-dir> [slug ...]

The page is the ENGLISH page, edited in place: every stylesheet, sprite and
layout block stays byte-identical, and only these change --

  head     <html lang>, title, description, canonical, og/twitter strings,
           og:locale, the Article node of the JSON-LD and the breadcrumbs
  links    the alternates block and the switcher, generated by langlinks.rewrite()
           -- the same code that maintains every other page
  chrome   header and footer text, and the five chrome links that have a
           Portuguese page (product, solutions, resources, about, contact).
           Pricing, the brand mark, privacy and terms stay English, by decision.
  wrap     back link, article head, main, rail, CTA, hero alt; every relative
           URL made root-absolute (href, src, srcset, imagesrcset, poster --
           README "the path trap")

Every replacement is asserted to fire the expected number of times, and the
chrome is checked as a SET afterwards: every text node left in the header and
footer must be Portuguese or on a short allowlist, so a label nobody put in the
map fails the build instead of shipping English. See README, "An enumeration
of names that looked complete".

The postflight is verify_pt.py, which runs over the whole document.
"""

import glob, html, io, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
I18N = os.path.dirname(HERE)
sys.path.insert(0, I18N)
import gate
import langlinks

SITE = "https://amazebase.pro"
LANG = "pt"
ARTICLES = "pt/artigos"
TOP = {"resources": "pt/recursos.html", "product": "pt/produto.html",
       "solutions": "pt/solucoes.html", "about": "pt/sobre.html",
       "contact": "pt/contato.html"}
# The manifest entry langlinks will get when all 51 exist. Until then it is
# used only to generate these pages' own alternates and switcher.
PT_ENTRY = {"code": "pt", "label": u"Português", "chip": "PT",
            "articles": ARTICLES, "top": TOP}

CHROME_HREF = {"/product.html": "/pt/produto.html", "/solutions.html": "/pt/solucoes.html",
               "/resources.html": "/pt/recursos.html", "/about.html": "/pt/sobre.html",
               "/contact.html": "/pt/contato.html"}

# Header/footer text nodes, English -> Portuguese (GLOSSARIO-PT.md section 4).
CHROME_TEXT = {
    "Product": "Produto",
    "Advertising &amp; PPC": "Publicidade e PPC",
    "Financials": "Finan&ccedil;as",
    "Inventory": "Estoque",
    "Product Research": "Pesquisa de produtos",
    "Simulations": "Simula&ccedil;&otilde;es",
    "Sales": "Vendas",
    "Data &amp; Sync": "Dados e sincroniza&ccedil;&atilde;o",
    "Security": "Seguran&ccedil;a",
    "AI Assistant &mdash; soon": "Assistente de IA &mdash; em breve",
    "Solutions": "Solu&ccedil;&otilde;es",
    "Beginners": "Iniciantes",
    "Experienced sellers": "Vendedores experientes",
    "Agencies": "Ag&ecirc;ncias",
    "Pricing": "Pre&ccedil;os",
    "Resources": "Recursos",
    "Company": "Empresa",
    "About": "Sobre",
    "Contact": "Contato",
    "Log in": "Entrar",
    "Join the Wait List": "Entre na lista de espera",
    "Knowledge Hub": "Central de Conhecimento",
    "Privacy": "Privacidade",
    "Terms": "Termos",
    "The operating system for Amazon sellers. Everything connected, everything in sync.":
        "O sistema operacional para vendedores da Amazon. Tudo conectado, tudo sincronizado.",
    ". All rights reserved.": ". Todos os direitos reservados.",
}
CHROME_ARIA = {
    "Primary": "Principal",
    "AmazeBase home": "P&aacute;gina inicial da AmazeBase",
    "Open menu": "Abrir menu",
}
# Text that is the same in every language. Anything else left in the chrome
# after the map has run is English that nobody mapped, and fails the build.
CHROME_KEEP = {"AmazeBase", "Ledger", "&copy; 2026", "EN", "ES", "PT", "English",
               u"Español", u"Português"}
ARIA_KEEP = {"Idioma / Language", "LinkedIn", "X", "GitHub"}

BACK = ('<p class="back-link"><a href="/pt/recursos.html">'
        '&larr; Central de Conhecimento</a></p>')
URL_ATTRS = ("href", "src", "srcset", "imagesrcset", "poster")


def rep(s, old, new, n=1, label=""):
    c = s.count(old)
    assert c == n, "expected %d of %r (%s), found %d" % (n, old[:80], label, c)
    return s.replace(old, new)


def region(s, start, end):
    i = s.index(start)
    j = s.index(end, i) + len(end)
    return i, j


def ld(v):
    """A JSON string body, \\u-escaped the way the Spanish pages carry it."""
    return json.dumps(v)[1:-1]


def load_cfg():
    cfg, slugs = langlinks.load()
    assert all(l["code"] != LANG for l in cfg["languages"]), \
        "pt is already in languages.json -- run langlinks, not this pilot path"
    cfg = dict(cfg, languages=cfg["languages"] + [PT_ENTRY])
    return cfg, slugs


# ------------------------------------------------------------------- chrome

def translate_chrome(seg, label):
    """Header or footer: links, then aria-labels, then text nodes; then the SET check."""
    for en, pt in CHROME_HREF.items():
        seg = re.sub(r'href="%s([#"])' % re.escape(en), lambda m: 'href="%s%s' % (pt, m.group(1)), seg)
    seg = re.sub(r'aria-label="([^"]*)"',
                 lambda m: 'aria-label="%s"' % CHROME_ARIA.get(m.group(1), m.group(1)), seg)

    def text(m):
        raw = m.group(1)
        core = raw.strip()
        if core in CHROME_TEXT:
            return ">" + raw.replace(core, CHROME_TEXT[core]) + "<"
        return m.group(0)
    seg = re.sub(r">([^<]+)<", text, seg)

    # the set check: every text node and aria-label is now Portuguese or allowed
    pt_vals = set(CHROME_TEXT.values()) | set(CHROME_ARIA.values())
    left = [t.strip() for t in re.findall(r">([^<]+)<", seg) if t.strip()]
    left = [t for t in left if t not in pt_vals and t not in CHROME_KEEP]
    aria = [a for a in re.findall(r'aria-label="([^"]*)"', seg)
            if a not in pt_vals and a not in ARIA_KEEP]
    assert not left and not aria, "%s: untranslated chrome %s %s" % (label, left, aria)
    return seg


# ---------------------------------------------------------------------- head

def head_seo(s, tr, en_url, pt_url, has_seo):
    s = rep(s, '<html lang="en">', '<html lang="pt">', label="html lang")
    s, n = re.subn(r"<title>.*?</title>",
                   lambda m: "<title>%s &mdash; AmazeBase</title>" % tr["title"], s, count=1, flags=re.S)
    assert n == 1, "title"
    s, n = re.subn(r'<meta name="description" content="[^"]*">',
                   lambda m: '<meta name="description" content="%s">' % tr["desc"], s, count=1)
    assert n == 1, "description"
    s = rep(s, '<link rel="canonical" href="%s">' % en_url,
               '<link rel="canonical" href="%s">' % pt_url, label="canonical")

    if not has_seo:
        # The late articles carry a small English OG set high in the head and
        # no SEO block. Drop that trio and add a complete Portuguese set after
        # the alternates -- the fixed Spanish shape (37c7b86), not the one
        # that shipped two og:title tags.
        for tag in ("og:title", "og:description", "og:type"):
            s, n = re.subn(r'<meta property="%s" content="[^"]*">\n' % tag, "", s, count=1)
            assert n == 1, "early %s" % tag
        m = langlinks.ALT_RUN.search(s)
        assert m, "no alternates run"
        og = ('<meta property="og:site_name" content="AmazeBase">\n'
              '<meta property="og:locale" content="pt_BR">\n'
              '<meta property="og:locale:alternate" content="en_US">\n'
              '<meta property="og:type" content="article">\n'
              '<meta property="og:url" content="%s">\n'
              '<meta property="og:title" content="%s">\n'
              '<meta property="og:description" content="%s">\n'
              % (pt_url, tr["og_title"], tr["og_desc"]))
        return s[:m.end()] + og + s[m.end():]

    s = rep(s, '<meta property="og:locale" content="en_US">',
               '<meta property="og:locale" content="pt_BR">\n'
               '<meta property="og:locale:alternate" content="en_US">', label="og:locale")
    s = rep(s, '<meta property="og:url" content="%s">' % en_url,
               '<meta property="og:url" content="%s">' % pt_url, label="og:url")
    for attr, key in (('property="og:title"', "og_title"), ('property="og:description"', "og_desc"),
                      ('name="twitter:title"', "og_title"), ('name="twitter:description"', "og_desc")):
        s, n = re.subn(r'<meta %s content="[^"]*">' % re.escape(attr),
                       lambda m: '<meta %s content="%s">' % (attr, tr[key]), s, count=1)
        assert n == 1, attr
    if tr.get("og_img_alt"):
        for attr in ('property="og:image:alt"', 'name="twitter:image:alt"'):
            s, n = re.subn(r'<meta %s content="[^"]*">' % re.escape(attr),
                           lambda m: '<meta %s content="%s">' % (attr, tr["og_img_alt"]), s, count=1)
            assert n == 1, attr

    # JSON-LD: the Article node and the breadcrumbs. WebSite keeps inLanguage
    # "en" -- it describes the site, which is English -- as the Spanish pages do.
    s = rep(s, '"@id": "%s#article"' % en_url, '"@id": "%s#article"' % pt_url, label="ld @id")
    s = rep(s, '"@id": "%s"\n      },\n      "headline"' % en_url,
               '"@id": "%s"\n      },\n      "headline"' % pt_url, label="ld mainEntityOfPage")
    s, n = re.subn(r'"headline": "[^"]*"', lambda m: '"headline": "%s"' % ld(tr["ld_headline"]), s, count=1)
    assert n == 1, "headline"
    s, n = re.subn(r'("headline": "[^"]*",\n      )"description": "[^"]*"',
                   lambda m: m.group(1) + '"description": "%s"' % ld(tr["ld_desc"]), s, count=1)
    assert n == 1, "ld description"
    parts = s.split('"inLanguage": "en"')
    assert len(parts) == 3, "expected 2 inLanguage nodes, found %d" % (len(parts) - 1)
    s = parts[0] + '"inLanguage": "en"' + parts[1] + '"inLanguage": "pt"' + parts[2]
    kw = '"keywords": [\n        %s\n      ]' % ",\n        ".join('"%s"' % ld(k) for k in tr["keywords"])
    s, n = re.subn(r'"keywords": \[.*?\]', lambda m: kw, s, count=1, flags=re.S)
    assert n == 1, "keywords"
    s = rep(s, '"name": "Home"', '"name": "%s"' % ld(u"Início"), label="crumb home")
    s = rep(s, '"name": "Knowledge Hub"', '"name": "Central de Conhecimento"', label="crumb hub")
    s = rep(s, '"item": "%s/resources.html"' % SITE, '"item": "%s/pt/recursos.html"' % SITE,
            label="crumb hub url")
    s, n = re.subn(r'("position": 3,\n          )"name": "[^"]*"',
                   lambda m: m.group(1) + '"name": "%s"' % ld(tr["crumb"]), s, count=1)
    assert n == 1, "crumb 3"
    return s


# ---------------------------------------------------------------------- body

def rootify(s):
    """Relative URLs root-absolute, on every URL-carrying attribute and every
    candidate inside a srcset list -- not only href/src (HANDOVER 1.4)."""
    def fix(u):
        u = u.strip()
        while u.startswith("../"):
            u = u[3:]
        return u if re.match(r"^(/|#|[a-z]+:)", u) else "/" + u

    def attr(m):
        name, val = m.group(1), m.group(2)
        if name in ("srcset", "imagesrcset"):
            parts = []
            for cand in val.split(","):
                bits = cand.strip().split(None, 1)
                parts.append(" ".join([fix(bits[0])] + bits[1:]))
            return '%s="%s"' % (name, ", ".join(parts))
        return '%s="%s"' % (name, fix(val))
    return re.sub(r'\b(%s)="([^"]*)"' % "|".join(URL_ATTRS), attr, s)


def build_one(tree, tr, cfg, slugs, pt_map):
    slug = tr["slug"]
    pt_slug = tr["pt_slug"]
    en_rel = "articles/%s.html" % slug
    pt_rel = "%s/%s.html" % (ARTICLES, pt_slug)
    en_url, pt_url = "%s/%s" % (SITE, en_rel), "%s/%s" % (SITE, pt_rel)
    s = io.open(os.path.join(tree, en_rel), encoding="utf-8", newline="").read()
    assert "\r" not in s, "English page is not LF"
    has_seo = "<!-- SEO:START -->" in s

    s = head_seo(s, tr, en_url, pt_url, has_seo)
    s = rep(s, ">Skip to content</a>", ">Pular para o conte&uacute;do</a>", label="skip link")

    a, b = region(s, '<header class="site-header">', "</header>")
    s = s[:a] + translate_chrome(s[a:b], "header") + s[b:]
    a, b = region(s, '<footer class="footer">', "</footer>")
    s = s[:a] + translate_chrome(s[a:b], "footer") + s[b:]

    # ---- the wrap block, edited in place
    i, j = region(s, '<div class="wrap">', "</div><!-- /.wrap -->")
    wrap = s[i:j]
    a, b = region(wrap, '<p class="back-link">', "</p>")
    wrap = wrap[:a] + BACK + wrap[b:]
    for field, start, end in (("article_head", '<header class="article-head">', "</header>"),
                              ("main", "<main", "</main>"),
                              ("rail", '<aside class="rail"', "</aside>"),
                              ("cta", '<aside class="cta">', "</aside>")):
        if tr.get(field) is None:
            assert start not in wrap, "%s: English has a %s, translation has none" % (slug, field)
            continue
        a, b = region(wrap, start, end)
        wrap = wrap[:a] + tr[field] + wrap[b:]
    live = re.sub(r"<!--.*?-->", " ", wrap, flags=re.S)
    has_hero = bool(re.search(r'<figure class="hero-shot">', live))
    assert has_hero == bool(tr.get("hero_alt")), "%s: hero/alt mismatch" % slug
    if has_hero:
        m = re.search(r'(<figure class="hero-shot">\s*<img\b[^>]*?\balt=")([^"]*)(")', wrap, re.S)
        assert m and "<!--" not in wrap[:m.start()][-200:], "%s: live hero not found" % slug
        wrap = wrap[:m.start(2)] + tr["hero_alt"] + wrap[m.end(2):]
    # cross-article links: to the Portuguese page where one exists, else left English
    wrap = re.sub(r'href="/articles/([a-z0-9-]+)\.html',
                  lambda m: 'href="/%s/%s.html' % (ARTICLES, pt_map[m.group(1)])
                  if m.group(1) in pt_map else m.group(0), wrap)
    wrap = rootify(wrap)
    s = s[:i] + wrap + s[j:]

    # ---- alternates + switcher, by the generator that maintains every page
    es = slugs.get("es") or {}
    members = {"en": en_rel, "pt": pt_rel}
    if slug in es:
        members["es"] = "es/articulos/%s.html" % es[slug]
    s = langlinks.rewrite(s, cfg, members, LANG)

    out = os.path.join(tree, pt_rel)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    io.open(out, "w", encoding="utf-8", newline="").write(s)
    return pt_rel


def main(tree, content, only=None):
    cfg, slugs = load_cfg()
    files = sorted(glob.glob(os.path.join(content, "*.json")))
    trs = [json.load(io.open(f, encoding="utf-8")) for f in files]
    if only:
        trs = [t for t in trs if t["slug"] in only]
    pt_map = dict((t["slug"], t["pt_slug"]) for t in trs)
    briefs = os.environ.get("PT_BRIEFS")
    assert briefs, "set PT_BRIEFS to the directory reextract.py wrote -- the gate runs first"
    built = []
    for t in trs:
        brief = json.load(io.open(os.path.join(briefs, t["slug"] + ".json"), encoding="utf-8"))
        n, prob = gate.audit(brief, t, LANG)
        assert not prob, "%s refused by the gate:\n  %s" % (t["slug"], "\n  ".join(prob))
        built.append((t["slug"], build_one(tree, t, cfg, slugs, pt_map), n, t["pt_slug"]))
    for slug, rel, n, sl in built:
        print("built  %-30s -> /%s   gate %d elements, slug %s"
              % (slug, rel, n, gate.slug_report(sl)))
    print("\n%d Portuguese pages built" % len(built))
    return built


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3:] or None)
